#!/bin/sh /etc/mk.rc.common

EXTRA_COMMANDS=""
EXTRA_HELP=""

PROG="$APP_DIR/bin/gopeed"

start_service() {
    procd_open_instance
    procd_set_param command $PROG -c $APP_DATA_DIR/config.json
#    GOPEED_ADDRESS="0.0.0.0" \
#    GOPEED_WHITEDOWNLOADDIRS="/root/downloads,/root/dir/*,/root/dir?abc"

    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

post_install() {
    local tmp_download="$MIKIT_TMP/gopeed.tar.gz"
    local url="${MIRROR}https://github.com/GopeedLab/gopeed/releases/download/v1.9.3/gopeed-web-v1.9.3-linux-${SYSTEM_ARCH}.zip"
    if ! curl -fSL --progress-bar --connect-timeout 5 "$url" -o "$tmp_download" || [ ! -s "$tmp_download" ]; then
        echo -e "\n ❌ 下载失败，请重新尝试卸载重装！"
        rm -f "$tmp_download" 2>/dev/null
        return 1
    fi
    mkdir -p "$APP_DIR/bin"
    unzip -q -o -j "$tmp_download" -d "$APP_DIR/bin/" 2>/dev/null
    [ ! -f "$APP_DATA_DIR/config.json" ] && init_conf
    chmod +x "$APP_DIR/bin/gopeed"

}

init_conf() {
    mkdir -p "$APP_DATA_DIR/download"
    cat > "$APP_DATA_DIR/config.json" << EOF
{
  "address": "0.0.0.0",
  "port": 9999,
  "username": "gopeed",
  "password": "",
  "apiToken": "",
  "storageDir": "$APP_DATA_DIR",
  "downloadConfig": {
    "downloadDir": "$APP_DATA_DIR/download"
  }
}
EOF
}

