#!/bin/sh /etc/mk.rc.common

EXTRA_COMMANDS=""
EXTRA_HELP=""

PROG="$APP_DIR/bin/rathole"
start_service() {
    local isserver=$(mikit_db get "isserver")
    local conf="client.toml"
    if [ "$isserver" = "1" ]; then
        conf="server.toml"
    fi
    procd_open_instance
    procd_set_param command $PROG "$APP_DATA_DIR/$conf"
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

post_install(){
    local tmp_download="$MIKIT_TMP/rathole.tar.gz"
    local arch="$SYSTEM_ARCH"
    local suffix="musl"
    case $SYSTEM_ARCH in
    arm64) arch="aarch64" ;;
    armv*)
      arch="arm"
      [ "$HARDWARE_COMPLETE" = "0" ] && suffix="musleabi" || suffix="musleabihf"
      ;;
    esac
    local url="${MIRROR}https://github.com/rathole-org/rathole/releases/download/v0.5.0/rathole-${arch}-unknown-linux-${suffix}.zip"
    if ! curl -fSL --progress-bar --connect-timeout 5 "$url" -o "$tmp_download" || [ ! -s "$tmp_download" ]; then
        echo -e "\n ❌ 下载失败，请重新尝试卸载重装！"
        rm -f "$tmp_download" 2>/dev/null
        return 1
    fi
    mkdir -p "$APP_DIR/bin"
    unzip -q -o "$tmp_download" -d "$APP_DIR/bin/" 2>/dev/null
    chmod -R +x "$APP_DIR/bin/"
    [ ! -f "$APP_DATA_DIR/server.toml" ] && init_conf
    return 0
}

init_conf() {
    cat > "$APP_DATA_DIR/server.toml" << EOF
[server]
bind_addr = "0.0.0.0:2333"           # 服务端监听客户端连接的主端口

[server.services.my_ssh]
token = "your_secret_token"          # 必须与客户端的 token 完全一致
bind_addr = "0.0.0.0:10022"          # 暴露访问的端口
EOF

    cat > "$APP_DATA_DIR/client.toml" << EOF
[client]
remote_addr = "X.X.X.X:2333"         # 指向服务端的地址和端口

[client.services.my_ssh]
token = "your_secret_token"          # 必须与服务端的 token 一致
local_addr = "127.0.0.1:22"          # 本地需要被映射的服务端口（例如 SSH 是 22）
EOF
}