#!/bin/sh /etc/mk.rc.common

EXTRA_COMMANDS=""
EXTRA_HELP=""

PROG="$APP_DIR/bin/gost"
#SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

start_service() {
    procd_open_instance
    procd_set_param command $PROG -C "$APP_DATA_DIR/config.json"
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

post_install(){
    local tmp_download="$MIKIT_TMP/gost.tar.gz"
    local arch="$SYSTEM_ARCH"

    case $SYSTEM_ARCH in
    armv*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="armv5" ;;
    mips*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="$arch-softfloat" || arch="$arch-hardfloat" ;;
    esac
    local url="${MIRROR}https://github.com/go-gost/gost/releases/download/v3.2.6/gost_3.2.6_linux_${arch}.tar.gz"
    if ! curl -fSL --progress-bar --connect-timeout 5 "$url" -o "$tmp_download" || [ ! -s "$tmp_download" ]; then
        echo -e "\n ❌ 下载失败，请重新尝试卸载重装！"
        rm -f "$tmp_download" 2>/dev/null
        return 1
    fi
    mkdir -p "$APP_DIR/bin"
    tar -xzf "$tmp_download" -C "$APP_DIR/bin/" 2>/dev/null
    chmod +x "$PROG"
    [ ! -f "$APP_DATA_DIR/config.json" ] && init_conf
    return 0
}

init_conf() {
    cat > "$APP_DATA_DIR/config.json" << EOF
{
  "services": [
    {
      "name": "my-proxy-server",
      "addr": ":1080",
      "handler": {
        "type": "socks5",
        "auth": {
          "username": "admin",
          "password": "your_password"
        }
      },
      "listener": {
        "type": "tcp"
      }
    }
  ]
}
EOF
}