#!/bin/sh /etc/mk.rc.common

EXTRA_COMMANDS=""
EXTRA_HELP=""

PROG="$APP_DIR/bin/openlist"

start_service() {
    procd_open_instance
    procd_set_param command $PROG server --data "$APP_DATA_DIR"
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

post_install() {
    local tmp_download="$MIKIT_TMP/openlist.tar.gz"
    local arch="musl-$SYSTEM_ARCH"

    case $SYSTEM_ARCH in
    arm64) : ;;
    armv7*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="musleabi-armv5l" || arch="musleabihf-armv7l" ;;
    armv*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="musleabi-armv5l" || arch="musleabihf-armv5l" ;;
    mips*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="musl-${SYSTEM_ARCH}le" ;;
    esac
    local url="${MIRROR}https://github.com/OpenListTeam/OpenList/releases/download/v4.2.5/openlist-linux-${arch}.tar.gz"
    if ! curl -fSL --progress-bar --connect-timeout 5 "$url" -o "$tmp_download" || [ ! -s "$tmp_download" ]; then
        echo -e "\n ❌ 下载失败，请重新尝试卸载重装！"
        rm -f "$tmp_download" 2>/dev/null
        return 1
    fi
    mkdir -p "$APP_DIR/bin"
    tar -zxf "$tmp_download" -C "$APP_DIR/bin/" 2>/dev/null
    chmod +x "$APP_DIR/bin/openlist"
}


