#!/bin/sh /etc/mk.rc.common

EXTRA_COMMANDS=""
EXTRA_HELP=""

PROG="$APP_DIR/bin/frpc"
start_service() {
    local isserver=$(mikit_db get "isserver")
    local type="c"
    local conf="client.toml"
    if [ "$isserver" = "1" ]; then
        PROG="$APP_DIR/bin/frps"
        conf="server.toml"
    fi
    procd_open_instance
    procd_set_param command $PROG -c "$APP_DATA_DIR/$conf"
    procd_set_param respawn
    procd_set_param stderr 1
    procd_close_instance
}

post_install(){
    local tmp_download="$MIKIT_TMP/frp.tar.gz"
    local arch="$SYSTEM_ARCH"

    case $SYSTEM_ARCH in
    armv*) [ "$HARDWARE_COMPLETE" = "0" ] && arch="arm" || arch="arm_hf" ;;
    esac
    local url="${MIRROR}https://github.com/fatedier/frp/releases/download/v0.71.0/frp_0.71.0_linux_${arch}.tar.gz"
    if ! curl -fSL --progress-bar --connect-timeout 5 "$url" -o "$tmp_download" || [ ! -s "$tmp_download" ]; then
        echo -e "\n ❌ 下载失败，请重新尝试卸载重装！"
        rm -f "$tmp_download" 2>/dev/null
        return 1
    fi
    mkdir -p "$APP_DIR/bin"
    tar -xzf "$tmp_download" -C "$APP_DIR/bin/" --strip-components=1 2>/dev/null
    chmod -R +x "$APP_DIR/bin/"
    [ ! -f "$APP_DATA_DIR/server.toml" ] && init_conf
    return 0
}

init_conf() {
    cat > "$APP_DATA_DIR/server.toml" << EOF
# 服务端监听客户端连接的端口
bindPort = 7000

# （可选）身份验证口令，客户端连接时必须与此一致
auth.token = "your_secure_token"

# （可选）后台管理面板配置
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
EOF

    cat > "$APP_DATA_DIR/client.toml" << EOF
# 服务端的 IP 地址
serverAddr = "X.X.X.X"
# 服务端的 bindPort
serverPort = 7000

# 必须与服务端的 auth.token 保持一致
auth.token = "your_secure_token"

# 定义具体的代理转发规则
[[proxies]]
name = "web-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22          # 你本地想要暴露的服务端口（例如 SSH 是 22）
remotePort = 10022      # 服务端开放的访问端口，外网通过服务端IP:60000来连你的SSH

EOF
}